### PR TITLE
GOOGLEDOCS-430 : Update GoogleDocs AMP version for ACS 6.0

### PR DESCRIPTION
**Pull request by CezarLeahu**
Updates the GoogleDocs AMPs to version 3.1.0.-RC1, which is compatible with ACS 6.* (updated dependencies, updated Spring configuration files).

### CODE REVIEW

**Comment by montgolfiere** [comment]
Thanks @CezarLeahu.

@andrei-rebegea  @killerboot please review.  Also, look out for similar PRs for Enterprise (& update to versions.md). If we've missed any other references, please let us know.

**Comment by killerboot** [comment]
@montgolfiere The changes look good. Don't forget to update Share project where the corresponding image is built.
@andrei-rebegea Do we still need the dependency for Google Doc's Share amp in the root pom?

**Comment by montgolfiere** [comment]
@killerboot Do you have a link to location of where Share builds the image, please ?

**Comment by killerboot** [comment]
@montgolfiere I think it is in 6.0 branch here: https://github.com/Alfresco/share/tree/6.0/packaging/docker

**Comment by montgolfiere** [comment]
@killerboot Thanks !

**Comment by tzclucian** [comment]
Merged as per @andrei-rebegea 's comment.

**Pull request merged**
